server:
  port: 8080

spring:
  application:
    name: messagingService
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

chat:
  redis:
    topic: chat-messages-${messaging.instance.id}

messaging:
  instance:
    id: ${random.uuid}
