spring:
  application:
    name: userService
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:destdb}
    username: ${DB_USER:destuser}
    password: ${DB_PASSWORD:destpassword123}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
